### PR TITLE
Fix PHP 7.1 incompatibility

### PR DESCRIPTION
**Pull request by akalongman**

### CODE REVIEW

**Comment by e1himself** [comment]
Good job! :+1: 
Thanks @akalongman!

**Comment by e1himself** [comment]
Also I felt it's not elegant to merge php7.1 fix into another feature branch.
So I've created another branch **forked** and merged **better-postgres-support** branch into it.
As well as your PHP 7.1 fix.

Now we need to switch our project to use **fork** branch instead of **better-postgres-support**.

@akalongman Can you do that please?
Thank you!

**Review by e1himself — COMMENTED** [review]
Good.

**Comment by akalongman** [comment]
Done, thanks

**Pull request merged**
